default_stages: [commit, push]
default_language_version:
  python: 3.8.10
repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    - id: black
      args: [
        --line-length=80, 
        --target-version=py38
      ]
      exclude: ^(venv/|.venv/|scripts/|docs/)
      types: ['python']
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      args: [
        --max-line-length=80
      ]
      exclude: ^(venv/|.venv/|scripts/|docs/)
      types: ['python']
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 0.9.4
  #   hooks:
  #   - id: sqlfluff-lint
  #     language: python
  #     require_serial: true
  #     exclude: ^(venv/|.venv/|.env|docs/)
  #     types: ['sql']
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true